[package]
name = "mod-parser"
version = "0.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
env_logger = "0.11.3"
# rfd = "0.12.1"
scraper = "0.19.0"
