[package]
name = "mod-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.8.3"
env_logger = "0.10.0"
# rfd = "0.12.1"
scraper = "0.18.1"
